services:
  - type: web
    name: embedboard-backend
    runtime: java
    rootDir: backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21

  - type: static
    name: embedboard-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_BASE
        value: https://embedboard-backend.onrender.com/api
